### ISSUE TITLE
下载下来只有480p的，是要会员才能下载1080p吗

### ISSUE THREAD

**Issue by tyzh279** [dfvips/viuparser#1]
下载下来只有480p的，是要会员才能下载1080p吗

**Comment by dfvips** [comment]
![image](https://user-images.githubusercontent.com/21048630/176191882-b7a0b297-0ee6-4ebd-bf87-24ea72d88cbf.png)
![image](https://user-images.githubusercontent.com/21048630/176192025-f2ca5755-7e5c-456e-852b-d8ca25584239.png)

我这边没有登录，测试下载出来的也是1080P。

**Comment by tyzh279** [comment]
搞错了，说的是lineTV，lineTV只能下480p的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dfvips/viuparser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dfvips/viuparser] 下载下来只有480p的，是要会员才能下载1080p吗 (Issue #1)





 

 
 
我这边没有登录，测试下载出来的也是1080P。

**Comment by dfvips** [comment]
是的。

**Comment by tyzh279** [comment]
有会员就可以下1080p了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月28日(星期二) 晚上10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dfvips/viuparser] 下载下来只有480p的，是要会员才能下载1080p吗 (Issue #1)





 
是的。

**Comment by dfvips** [comment]
是的
