### ISSUE TITLE
之后会支持下新加坡区和注释字幕吗

### ISSUE THREAD

**Issue by hihaozhe** [dfvips/viuparser#2]
现在新加坡区和注释字幕貌似还不行，之后可能会支持吗

**Comment by dfvips** [comment]
已增加，请更新新版本测试。

**Comment by dfvips** [comment]
注释字幕指的是什么？在播放页面的字幕列表里面有吗？

**Comment by hihaozhe** [comment]
视频链接：https://www.viu.com/ott/hk/zh-hk/vod/456101/The-Empire-%E6%B3%95%E4%B9%8B%E5%B8%9D%E5%9C%8B%E2%80%8B
字幕接口里的链接：{"is_default":1,"name":"u7e41u9ad4u4e2du6587","url":"https://d2anahhhmp1ffz.cloudfront.net/2034048069/e786a293fc98bb394198d7e500205c41a47bc563","subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/2034048069/e786a293fc98bb394198d7e500205c41a47bc563","product_subtitle_id":"260506","product_subtitle_language_id":"1","second_subtitle_url":"https://d2anahhhmp1ffz.cloudfront.net/4008691149/f8e0e2e27b4c4433c484646ad48223de908b4782","second_subtitle_position":0,"code":"zh-Hant"}],
这里的second_subtitle_url就加了注释

**Comment by hihaozhe** [comment]
url里是字幕正文，second_subtitle_url是一些场景翻译和片头演员的注释

**Comment by hihaozhe** [comment]
新加坡区已经测试过了，很正常，辛苦了

**Comment by dfvips** [comment]
已增加，请更新新版本测试。
