### ISSUE TITLE
真的好好用！！！可以拜托大大再增加一下印尼嘛，有部剧只有印尼有

### ISSUE THREAD

**Issue by artemisluck97** [dfvips/viuparser#4]
https://www.viu.com/ott/id/en/all/video-mandarin-drama-tv_shows-lucky_with_you_episode_1-1165961121?containerId=playlist-26272315
这个是印尼的，印尼有时候会风控，如果弹出风控界面的话可能需要把wifi切成流量之类的，辛苦大大，期待支持东南亚更多国家！！

**Comment by artemisluck97** [comment]
或者菲律宾也行呜呜呜

**Comment by dfvips** [comment]
没有你写的地区的节点。

**Comment by artemisluck97** [comment]
> 没有你写的地区的节点。

我有菲区节点的订阅链接，不知道还剩几天，发到大佬邮箱啦，请查收~ 发到了您这个邮箱dfvips@qq.com，不知道您有没有收到~

**Comment by dfvips** [comment]
![7935cbdd094bb87c5e126c8e7c0e3745](https://user-images.githubusercontent.com/21048630/205441959-2635fe41-d8e6-46fc-b3af-24656da3e194.png)
![681d761c836f873a8cf5810f6ea9044e](https://user-images.githubusercontent.com/21048630/205442030-b1d25cb5-5273-4afb-9449-40288265b01f.png)
我测试你的订阅里面菲律宾区的链接，解析正常的。

**Comment by dfvips** [comment]
印尼那个链接，没有节点打不开
